feat: Реализован сервер статистики
EvgeniyUdin1979/java-explore-with-me pull request #3
Opened 2023-07-06 15:16 UTC by EvgeniyUdin1979

2023-07-07 17:47 UTC, AnastasiyaFomkina requested changes
Три реализованных модуля должны быть частью большого модуля статистики, также
нужно добавить основной модуль `main` и `docker-compose` для него. 
Посмотри, пожалуйста, внимательно часть `Как подготовить сборку проекта` в тз проекта и поправь структуру по тз

2023-07-07 17:47 UTC, AnastasiyaFomkina commented on pom.xml
> +	<dependencies>
Блок `dependencies` нужно убрать из родительского  `pom` файла

2023-07-07 17:47 UTC, AnastasiyaFomkina commented on stats/statsclient/src/main/java/ru/practicum/Main.java
> +public class Main {
Лишний класс

2023-07-07 17:47 UTC, AnastasiyaFomkina commented on stats/statsclient/src/main/java/ru/practicum/client/StatsClient.java
> +                Map.of("start", params.getStart().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")),
Паттерн нужно вынести в константу, чтобы избавиться от дублирований

2023-07-07 17:47 UTC, AnastasiyaFomkina commented on stats/statsclient/.gitignore
> +target/
`.gitignore` должен быть только один на весь проект и он должен находиться в корне проекта

2023-07-07 17:47 UTC, AnastasiyaFomkina commented on stats/statsclient/pom.xml
> +            <artifactId>junit-jupiter-api</artifactId>
В данном модуле нет тестов, поэтому эта зависимость лишняя

2023-07-07 17:47 UTC, AnastasiyaFomkina commented on stats/statscommondto/pom.xml
> +<!--        <dependency>-->
Закомментированный код нужно удалить

2023-07-07 17:47 UTC, AnastasiyaFomkina commented on stats/statscommondto/src/main/java/ru/practicum/Main.java
> +public class Main {
Лишний класс

2023-07-07 17:47 UTC, AnastasiyaFomkina commented on stats/statscommondto/src/main/java/ru/practicum/dto/StatsOutDto.java
> +
Лишние отступы

2023-07-07 17:47 UTC, AnastasiyaFomkina commented on stats/statsserver/src/main/java/ru/practicum/stats/controllers/StatsController.java
> +            @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
Нужно выделить в публичную константу и переиспользовать во всем модуле

2023-07-07 17:47 UTC, AnastasiyaFomkina commented on stats/statscommondto/src/main/resources/application.properties
Файл пустой, нужно удалить

2023-07-07 17:47 UTC, AnastasiyaFomkina commented on stats/statsserver/src/main/java/ru/practicum/stats/controllers/StatsController.java
> +    public StatsController(StatsService service) {
Нужно использовать [@Autowired](https://www.baeldung.com/spring-autowire) над конструктором

2023-07-07 17:47 UTC, AnastasiyaFomkina commented on stats/statsserver/src/main/java/ru/practicum/stats/controllers/StatsController.java
> +        ParamGet params = ParamGet.builder()
Создание `ParamGet` - часть бизнес-логики программы, она должна быть на уровне сервиса

2023-07-07 17:47 UTC, AnastasiyaFomkina commented on stats/statsserver/src/main/java/ru/practicum/stats/exceptions/RequestException.java
> +    public RequestException() {
Этот конструктор не используется, нужно удалить

2023-07-07 17:47 UTC, AnastasiyaFomkina commented on stats/statsserver/src/test/java/ru/practicum/stats/storage/StatsStorageImplTest.java
> +class StatsStorageImplTest {
Клево, что написал тесты 🔥

2023-07-07 17:47 UTC, AnastasiyaFomkina commented on stats/statsserver/src/test/java/ru/practicum/stats/storage/StatsStorageImplTest.java
> +    StatsStorage storage;
Не хватает модификатора доступа

2023-07-08 09:03 UTC, EvgeniyUdin1979 commented on stats/statsclient/src/main/java/ru/practicum/Main.java
> +public class Main {
убрал.

2023-07-08 12:24 UTC, EvgeniyUdin1979 commented on pom.xml
> +	<dependencies>
Наставник на вебинаре рассказывал, что общие зависимости можно прописывать в родительском  пом

2023-07-08 14:00 UTC, EvgeniyUdin1979 commented on stats/statsserver/src/main/java/ru/practicum/stats/exceptions/RequestException.java
> +    public RequestException() {
удалил

2023-07-08 14:03 UTC, EvgeniyUdin1979 commented on stats/statsserver/src/main/java/ru/practicum/stats/controllers/StatsController.java
> +        ParamGet params = ParamGet.builder()
наставник разрешил оставить, но переименовать в StatParam.

2023-07-08 14:04 UTC, EvgeniyUdin1979 commented on stats/statsserver/src/main/java/ru/practicum/stats/controllers/StatsController.java
> +    public StatsController(StatsService service) {
добавил

2023-07-08 14:06 UTC, EvgeniyUdin1979 commented on stats/statsserver/src/test/java/ru/practicum/stats/storage/StatsStorageImplTest.java
> +    StatsStorage storage;
Добавил.

2023-07-08 14:06 UTC, EvgeniyUdin1979 commented on stats/statsclient/pom.xml
> +            <artifactId>junit-jupiter-api</artifactId>
удалил

2023-07-08 14:06 UTC, EvgeniyUdin1979 commented on stats/statsclient/.gitignore
> +target/
удалил

2023-07-08 14:06 UTC, EvgeniyUdin1979 commented on stats/statsclient/src/main/java/ru/practicum/client/StatsClient.java
> +                Map.of("start", params.getStart().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")),
сделал

2023-07-08 23:28 UTC, AnastasiyaFomkina approved these changes
Оставила несколько комментариев просто для информации, можно поправить, если будет желание

2023-07-08 23:28 UTC, AnastasiyaFomkina commented on stats/statsclient/src/main/java/ru/practicum/client/StatsClient.java
> +    private final String dateTimeFormat = "yyyy-MM-dd HH:mm:ss";
FYI
Константы в java обычно имеют сочетание модификаторов [static final](https://www.theserverside.com/video/Why-we-use-static-final-in-Java-for-constants#:~:text=The%20static%20keyword%20means%20the,to%20create%20a%20constant%20value.) и именуются в CAMEL_CASE
```suggestion
    private static final String DATE_TIME_FORMAT = "yyyy-MM-dd HH:mm:ss";
```

2023-07-08 23:28 UTC, AnastasiyaFomkina commented on stats/statscommondto/src/main/java/ru/practicum/dto/StatsOutDto.java
> +
Лишние отступы

2023-07-08 23:28 UTC, AnastasiyaFomkina commented on stats/statscommondto/pom.xml
> +<!--        <dependency>-->
Закомментированный код нужно удалить

2023-07-08 23:51 UTC, merged