Второй этап дипломной работы.
EvgeniyUdin1979/java-explore-with-me pull request #4
Opened 2023-07-22 16:19 UTC by EvgeniyUdin1979

2023-07-24 17:12 UTC, AnastasiyaFomkina requested changes

2023-07-24 17:12 UTC, AnastasiyaFomkina commented on main/src/main/java/ru/practicum/users/storage/UserRepository.java
> +    Page<User> findAllByIdIn(List<Long> ids, Pageable pageable);
Лучше заменить `Page` на `List`, выборка никак не изменится, но не придется самостоятельно преобразовывать `Page` в `List` в сервисе

2023-07-24 17:12 UTC, AnastasiyaFomkina commented on main/src/main/resources/schema.sql
_Опционально_
Предлагаю попробовать добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/), чтобы ускорить поиск

2023-07-25 11:15 UTC, EvgeniyUdin1979 commented on main/src/main/java/ru/practicum/advices/CustomAdvice.java
> +    String reasonBadRequest = "Некорректные параметры запроса.";
Сделал.

2023-07-25 11:15 UTC, EvgeniyUdin1979 commented on main/src/main/java/ru/practicum/advices/CustomAdvice.java
> +    ResponseEntity<ApiError> handler(RequestException e) {
Сделал.

2023-07-25 11:18 UTC, EvgeniyUdin1979 commented on main/src/main/java/ru/practicum/categories/service/CategoryServiceImpl.java
> +    public CategoryServiceImpl(CategoryStorageDao storage) {
Меня не смущает однотипный код. Так нагляднее и понятнее по моему чем всё заменять аннотациями из ломбока, а потом искать проблемы в коде которого нет. Я бы хотел это оставить как есть.

2023-07-25 11:19 UTC, EvgeniyUdin1979 commented on main/src/main/java/ru/practicum/categories/service/CategoryServiceImpl.java
> +        return categories.stream().map(CategoryMapping::mapToOut).collect(Collectors.toList());
Сделал.

2023-07-25 11:53 UTC, EvgeniyUdin1979 commented on main/src/main/java/ru/practicum/compilations/service/CompilationServiceImpl.java
> +            LocalDateTime start = events.stream().min(Comparator.comparing(Event::getCreated)).get().getCreated();
Вынес в отдельный класс.

2023-07-25 11:56 UTC, EvgeniyUdin1979 commented on main/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +                long v = 0;
переименовал в viewHits.

2023-07-25 11:59 UTC, EvgeniyUdin1979 commented on main/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +        for (Request request : requests) {
Да я знаю об этом и использую, но считаю излишним каждый цикл превращать в стрим. В данном случае стрим не несет никакой дополнительной выгоды и по тому излишен.

2023-07-25 12:02 UTC, EvgeniyUdin1979 commented on main/src/main/java/ru/practicum/users/storage/UserRepository.java
> +    Page<User> findAllByIdIn(List<Long> ids, Pageable pageable);
Сделал. На досуге почитаю в чем у них разница.

2023-07-25 13:06 UTC, EvgeniyUdin1979 commented on main/src/main/resources/schema.sql
Почитал и посмотрел информацию в интернете. Не рекомендуется использовать индексы и небольшим таблицам и часто изменяемым данным. Это требует осмысления и не уверен что смогу сейчас правильно настроить индексацию.

2023-07-26 08:01 UTC, AnastasiyaFomkina commented on main/src/main/java/ru/practicum/events/util/EventMapping.java
> +        switch (action) {
Можно добавлять еще параметры, но тут тоже нужно соблюдать баланс, чтобы не разрастить enum в огромного монстра

2023-07-26 08:04 UTC, AnastasiyaFomkina approved these changes

2023-07-26 10:04 UTC, merged